services:
  api_server:
    container_name: api_server
    image: api
    command: "fastapi dev --host 0.0.0.0"
    volumes:
      - ./app:/code/app
      - ./data:/code/data
    ports:
      - "8000:8000"
    environment:
      DB_FILE_PATH: /data/api.db
