services:
  api_server:
    container_name: api_server
    image: api
    command: "fastapi dev --host 0.0.0.0"
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: api
    networks:
      - api

  db:
    container_name: db
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    networks:
      - api

networks:
  api:
    driver: bridge
