services:
  api_server:
    container_name: api_server
    image: api
    ports:
      - "8000:8000"

  db:
    container_name: db
    image: postgres:16.3
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
