FROM nginx:mainline-alpine-slim

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY apiclub.com.pem /etc/nginx/apiclub.com.pem

COPY apiclub.com-key.pem /etc/nginx/apiclub.com-key.pem

CMD ["nginx", "-g", "daemon off;"]
